/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'xs': '420px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      'short': { raw: '(max-height: 500px)' },
    },
    extend: {
      fontSize: {
        '2xs': ['12px', { lineHeight: '16px' }],
        'xs': ['13px', { lineHeight: '18px' }],
        'sm': ['14px', { lineHeight: '20px' }],
        'base': ['16px', { lineHeight: '24px' }],
        'lg': ['18px', { lineHeight: '26px' }],
        'xl': ['20px', { lineHeight: '28px' }],
        '2xl': ['clamp(1.35rem, 2.5vw, 1.65rem)', { lineHeight: '1.25' }],
        '3xl': ['clamp(1.65rem, 3.5vw, 2.15rem)', { lineHeight: '1.2' }],
        '4xl': ['clamp(2rem, 5vw, 2.75rem)', { lineHeight: '1.15' }],
      },
      colors: {
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-raised': 'var(--surface-raised)',
        text: {
          DEFAULT: 'var(--text)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
        },
        border: {
          DEFAULT: 'var(--border)',
          subtle: 'var(--border-subtle)',
        },
        brand: {
          DEFAULT: 'var(--brand)',
          hover: 'var(--brand-hover)',
        },
        sage: {
          DEFAULT: 'var(--sage)',
          subtle: 'var(--sage-subtle)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          contrast: 'var(--accent-contrast)',
          subtle: 'var(--accent-subtle)',
          text: 'var(--accent-text)',
        },
        cat: {
          cooperative: 'var(--cat-cooperative)',
          'cooperative-subtle': 'var(--cat-cooperative-subtle)',
          social: 'var(--cat-social)',
          'social-subtle': 'var(--cat-social-subtle)',
          competitive: 'var(--cat-competitive)',
          'competitive-subtle': 'var(--cat-competitive-subtle)',
          energizer: 'var(--cat-energizer)',
          'energizer-subtle': 'var(--cat-energizer-subtle)',
          service: 'var(--cat-service)',
          'service-subtle': 'var(--cat-service-subtle)',
          arts: 'var(--cat-arts)',
          'arts-subtle': 'var(--cat-arts-subtle)',
          devotional: 'var(--cat-devotional)',
          'devotional-subtle': 'var(--cat-devotional-subtle)',
          study: 'var(--cat-study)',
          'study-subtle': 'var(--cat-study-subtle)',
        },
        // Apple tokens mapped dynamically to CSS variables for backwards compatibility
        apple: {
          bg: 'var(--bg)',
          surface: 'var(--surface)',
          border: 'var(--border)',
          subtle: 'var(--border-subtle)',
          text: 'var(--text)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          blue: 'var(--brand)',
          blueHover: 'var(--brand-hover)',
          green: 'var(--sage)',
          amber: 'var(--accent)',
        },
      },
      fontFamily: {
        sans: [
          '"Figtree"',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'sans-serif',
        ],
        serif: ['"Lora"', '"Playfair Display"', 'Georgia', 'serif'],
      },
      boxShadow: {
        'apple-card': '0 2px 14px rgba(14, 32, 51, 0.05)',
        'apple-card-hover': '0 10px 28px rgba(14, 32, 51, 0.09)',
        'apple-pill': '0 2px 8px rgba(14, 32, 51, 0.07)',
        'apple-modal': '0 20px 50px rgba(9, 19, 32, 0.35)',
      },
      zIndex: {
        '60': '60',
        '70': '70',
      },
    },
  },
  plugins: [],
}
